base_dockerfile_template: |
  ARG JAVA_VERSION=8
  ARG HADOOP_VERSION=3.2.1

  FROM mpolatcan/hadoop:${{HADOOP_VERSION}}-java${{JAVA_VERSION}}

  MAINTAINER Mutlu Polatcan <mutlupolatcan@gmail.com>

  ENV PIG_HOME "${{HDUSER_HOME}}/pig"
  ENV PIG_CONF_DIR="${{PIG_HOME}}/conf" \
      PATH=$PATH:$PIG_HOME/bin \
  {env_vars}

  ADD entrypoint.sh ${{HDUSER_HOME}}/pig_entrypoint.sh
  ADD config_loader.sh ${{HDUSER_HOME}}/pig_config_loader.sh

  USER root
  RUN mkdir -p ${{PIG_HOME}} && \
      chmod +x pig_config_loader.sh pig_entrypoint.sh

config_loader_sh_template: |
  #!/usr/bin/env bash
  function load_config() {{
    if [[ "$2" != "NULL" ]]
      then
        printf "$1=$2\n" >> "${{PIG_CONF_DIR}}/$3"
    fi
  }}

  printf "" > "${{PIG_CONF_DIR}}/pig.properties"
  {load_fn_calls}

config_files:
  - path: pig_configs/pig-properties.yaml
    filename: pig.properties

output_dir: ../../base