config_loader_sh_template: |
  #!/usr/bin/env bash
  function load_config() {{
    if [[ "$2" != "NULL" ]]
      then
        printf "$1=$2\n" >> "${{PIG_CONF_DIR}}/$3"
    fi
  }}

  printf "" > "${{PIG_CONF_DIR}}/pig.properties"
  {load_fn_calls}

config_files:
  - path: pig-properties.yaml
    filename: pig.properties
