name: pig-docker

on:
  push:
    branches:
      - master

jobs:
  build-base-hadoop-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: [pig]
        java_version: [8]
        hadoop_version: [3.3.0, 3.2.1, 3.1.4, 2.10.1, 2.9.2, 2.8.5]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - run: |
          cd src/base
          python pig_config_loader_generator.py config.yaml
      - run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - run: docker build -q
           -t ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:base-hadoop-${{matrix.hadoop_version}}-java${{matrix.java_version}}
           --build-arg HADOOP_IMAGE_TAG=${{matrix.hadoop_version}}-java${{matrix.java_version}}
           src/base
      - run: docker push ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:base-hadoop-${{matrix.hadoop_version}}-java${{matrix.java_version}}
      - run: docker rmi ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:base-hadoop-${{matrix.hadoop_version}}-java${{matrix.java_version}}

  build-base-hadoop-with-tez-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: [pig]
        java_version: [8]
        hadoop_version: [2.10.1, 2.9.2, 2.8.5]
        tez_version: [0.9.2]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - run: |
          cd src/base
          python pig_config_loader_generator.py config.yaml
      - run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - run: docker build -q
          -t ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:base-hadoop-${{matrix.hadoop_version}}-tez-${{matrix.tez_version}}-java${{matrix.java_version}}
          --build-arg HADOOP_IMAGE_TAG=${{matrix.hadoop_version}}-tez-${{matrix.tez_version}}-java${{matrix.java_version}}
          src/base
      - run: docker push ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:base-hadoop-${{matrix.hadoop_version}}-tez-${{matrix.tez_version}}-java${{matrix.java_version}}
      - run: docker rmi ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:base-hadoop-${{matrix.hadoop_version}}-tez-${{matrix.tez_version}}-java${{matrix.java_version}}

  build-pig-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: [pig]
        java_version: [8]
        pig_version: [0.17.0, 0.16.0]
        hadoop_version: [3.3.0, 3.2.1, 3.1.4, 2.10.1, 2.9.2, 2.8.5]
    needs: build-base-hadoop-image
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - run: docker build -q
          -t ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.pig_version}}-hadoop-${{matrix.hadoop_version}}-java${{matrix.java_version}}
          --build-arg PIG_VERSION=${{matrix.pig_version}}
          --build-arg HADOOP_VERSION=${{matrix.hadoop_version}}
          --build-arg JAVA_VERSION=${{matrix.java_version}}
          src/pig
      - run: docker push ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.pig_version}}-hadoop-${{matrix.hadoop_version}}-java${{matrix.java_version}}
      - run: docker rmi ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.pig_version}}-hadoop-${{matrix.hadoop_version}}-java${{matrix.java_version}}

  build-pig-with-tez-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: [pig]
        java_version: [8]
        pig_version: [0.17.0, 0.16.0]
        hadoop_version: [2.10.1, 2.9.2, 2.8.5]
        tez_version: [0.9.2]
    needs: build-base-hadoop-image
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - run: docker build -q
          -t ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.pig_version}}-hadoop-${{matrix.hadoop_version}}-tez-${{matrix.tez_version}}-java${{matrix.java_version}}
          --build-arg PIG_VERSION=${{matrix.pig_version}}
          --build-arg HADOOP_VERSION=${{matrix.hadoop_version}}
          --build-arg TEZ_VERSION=${{matrix.tez_version}}
          --build-arg JAVA_VERSION=${{matrix.java_version}}
          src/pig_with_tez
      - run: docker push ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.pig_version}}-hadoop-${{matrix.hadoop_version}}-tez-${{matrix.tez_version}}-java${{matrix.java_version}}
      - run: docker rmi ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.pig_version}}-hadoop-${{matrix.hadoop_version}}-tez-${{matrix.tez_version}}-java${{matrix.java_version}}